### ISSUE TITLE
변경사항 요청

### ISSUE THREAD

**Issue by oct-sky-out** [Gaship/gaship-scheduler#2]
1. DataprotectionConfig에서 spring security의 Bcrypt도 끌고오셨던데, 이건 따로 용도가 있으셔서 그런건가요?
2. Dev .properties설정 잘못되었어요.
3. 그리고 이건 저희 모든 프로젝트의 문제이긴한데... gaship.gashipscheduler 같은 패키지 명으로 지정시 체크스타일 주의가 발생해요 이걸 gaship.scheduler...으로 가져가면 앞으로 체크스타일 오류가 발생은 하지않을거에요, 다른 프로젝트의 패키지도 마찬가지로 다 공사해야합니다 이건

@SemiKimm

**Comment by semilaver** [comment]
1. data protection 관련해서 되어 있길래 저희 security key 에 사용되는줄 알았습니다. 확인해보니 해당 부분 없어도 되는 부분이네요 feature/setting 에서 1,2,3 내용 수정해서 다시 머지 시키도록 하겠습니다:)
